package de.baum2dev.baum2.entity;

import software.bernie.geckolib.animation.RawAnimation;

/**
 * Shared GeckoLib animation constants for every "fallen comet stone" mini-boss (Stone of
 * Spiders, Stone of Zombies, ...). All stone bosses share one geometry + one animation file
 * (assets/baum2/geckolib/{models,animations}/entity/fallen_comet_stone.*, generated by
 * tools/gen_fallen_comet_stone.py) and differ only by texture - see that script's docstring
 * for the full template contract. Keeping the animation name here (instead of a copy per
 * entity) means a typo can't silently desync one stone from the shared animation file.
 */
public final class FallenCometStoneAnimations {

    /** 12s seamless loop: the knocked-loose glowing shards orbit, bob, and self-spin. */
    public static final RawAnimation IDLE =
            RawAnimation.begin().thenLoop("animation.fallen_comet_stone.idle");

    private FallenCometStoneAnimations() {
    }
}
