package de.baum2dev.baum2.entity;

import java.util.EnumSet;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import net.minecraft.block.BlockState;
import net.minecraft.entity.EntityType;
import net.minecraft.entity.LivingEntity;
import net.minecraft.entity.MovementType;
import net.minecraft.entity.ai.goal.ActiveTargetGoal;
import net.minecraft.entity.ai.goal.Goal;
import net.minecraft.entity.ai.goal.LookAroundGoal;
import net.minecraft.entity.ai.goal.LookAtEntityGoal;
import net.minecraft.entity.ai.goal.RevengeGoal;
import net.minecraft.entity.ai.goal.WanderAroundFarGoal;
import net.minecraft.entity.attribute.DefaultAttributeContainer;
import net.minecraft.entity.attribute.EntityAttributes;
import net.minecraft.entity.damage.DamageSource;
import net.minecraft.entity.data.DataTracker;
import net.minecraft.entity.data.TrackedData;
import net.minecraft.entity.data.TrackedDataHandlerRegistry;
import net.minecraft.entity.mob.ZombieEntity;
import net.minecraft.entity.player.PlayerEntity;
import net.minecraft.item.ItemStack;
import net.minecraft.particle.BlockStateParticleEffect;
import net.minecraft.particle.ParticleTypes;
import net.minecraft.server.world.ServerWorld;
import net.minecraft.sound.SoundEvents;
import net.minecraft.util.math.BlockPos;
import net.minecraft.util.math.Box;
import net.minecraft.util.math.Vec3d;
import net.minecraft.util.math.random.Random;
import net.minecraft.world.LocalDifficulty;
import net.minecraft.world.World;
import de.baum2dev.baum2.combat.BurnDamageManager;
import de.baum2dev.baum2.registry.ModItems;
import software.bernie.geckolib.animatable.GeoEntity;
import software.bernie.geckolib.animatable.instance.AnimatableInstanceCache;
import software.bernie.geckolib.animatable.manager.AnimatableManager;
import software.bernie.geckolib.animation.AnimationController;
import software.bernie.geckolib.animation.RawAnimation;
import software.bernie.geckolib.animation.object.PlayState;
import software.bernie.geckolib.animation.state.AnimationTest;
import software.bernie.geckolib.util.GeckoLibUtil;

/**
 * A mobile boss (same family as SpiderQueenEntity - a giant 3x-scaled brute that walks/chases,
 * not a stationary "Stone of" totem): a hulking zombie warlord fighting with a slow, heavy
 * club. Extends vanilla ZombieEntity directly (not HostileEntity) to inherit undead traits and
 * zombie AI plumbing for free - goals, attributes, equipment, and drop are overridden.
 *
 * <p>Rendering/animation is GeckoLib-based (second mob after Spider Queen): bespoke muscular
 * geometry generated by tools/gen_zombie_colossus.py (the Colossal Warclub is a real "club"
 * bone in that model, not a held item), animations by tools/gen_zombie_colossus_anims.py -
 * those scripts' docstrings define the server-timing contracts (smash damage delay, rage
 * strike ticks, leap windup/flight lengths, earthquake slam tick) that the Goals below must
 * stay in lockstep with. Visual 3x scale is the renderer's withScale(3.0F); the hitbox is
 * EntityType.Builder.dimensions() (unchanged).
 */
public class ZombieColossusEntity extends ZombieEntity implements MonsterLevelProvider, GeoEntity {
    private static final int LEVEL = 25;

    // --- GeckoLib animation wiring (same pattern as SpiderQueenEntity). One controller:
    // state-driven idle/walk/leap poses, plus three server-triggered one-shots (smash/rage/
    // earthquake) registered as triggerable animations - GeckoLib syncs triggers to clients
    // itself, no custom TrackedData needed for them.
    private final AnimatableInstanceCache geoCache = GeckoLibUtil.createInstanceCache(this);

    private static final RawAnimation IDLE_ANIM = RawAnimation.begin().thenLoop("animation.zombie_colossus.idle");
    private static final RawAnimation WALK_ANIM = RawAnimation.begin().thenLoop("animation.zombie_colossus.walk");
    private static final RawAnimation LEAP_WINDUP_ANIM =
            RawAnimation.begin().thenPlay("animation.zombie_colossus.leap_windup");
    private static final RawAnimation LEAP_FLIGHT_ANIM =
            RawAnimation.begin().thenPlay("animation.zombie_colossus.leap_flight");
    private static final RawAnimation SMASH_ANIM = RawAnimation.begin().thenPlay("animation.zombie_colossus.smash");
    private static final RawAnimation RAGE_ANIM = RawAnimation.begin().thenPlay("animation.zombie_colossus.rage");
    private static final RawAnimation EARTHQUAKE_ANIM =
            RawAnimation.begin().thenPlay("animation.zombie_colossus.earthquake");
    static final String MAIN_CONTROLLER = "main";

    // --- Leap flight arc (see SpiderQueenEntity's HORIZONTAL_HEIGHTS/FRACTIONS javadoc for how
    // this style of table is derived and why direct position control, not setVelocity(), is
    // used - two rounds of velocity-based leaps failed in this exact codebase before that fix).
    // A single "fast forward-and-up" profile is enough here - no elevated-target case was
    // requested for this boss, unlike Spider Queen's two-profile leap.
    private static final double[] LEAP_HEIGHTS = {
            0.35, 0.68, 0.95, 1.15, 1.30, 1.38, 1.40, 1.35, 1.24, 1.06, 0.82, 0.51, 0.14, -0.30
    };
    private static final double[] LEAP_FRACTIONS = {
            0.09, 0.19, 0.29, 0.39, 0.48, 0.57, 0.65, 0.73, 0.80, 0.87, 0.92, 0.96, 0.99, 1.00
    };

    // Synced to the client so the leap's telegraph/flight animations can be selected by the
    // GeckoLib controller - same mechanism SpiderQueenEntity established. (The old
    // RAGE_WINDUP_TICKS TrackedData is gone: the rage combo is a single triggered animation
    // now, GeckoLib's own trigger sync covers it.)
    private static final TrackedData<Integer> LEAP_WINDUP_TICKS =
            DataTracker.registerData(ZombieColossusEntity.class, TrackedDataHandlerRegistry.INTEGER);
    private static final TrackedData<Boolean> LEAP_FLIGHT_ACTIVE =
            DataTracker.registerData(ZombieColossusEntity.class, TrackedDataHandlerRegistry.BOOLEAN);

    private int leapCooldownTicks = 0;
    private int rageCooldownTicks = 0;
    private int earthquakeCooldownTicks = 0;
    // Entity-level like the other three (balance-reviewer finding): this used to live on
    // ColossusAttackGoal and got reset to 0 in start() every time a higher-priority goal
    // (rage/leap/earthquake) preempted and returned control - letting the base attack fire
    // again immediately and quietly inflating real burst beyond the "100 dmg / 2s" spec.
    private int attackCooldownTicks = 0;

    // Leap flight state - owned by the entity because it's driven from travel(), same pattern
    // as SpiderQueenEntity.
    private int leapFlightTicksRemaining = 0;
    private int leapFlightTotalTicks = 0;
    private double leapFlightHorizontalDistance = 0.0;
    private double leapFlightPrevFraction = 0.0;
    private double leapFlightPrevHeight = 0.0;
    private Vec3d leapFlightDirection = Vec3d.ZERO;

    // Fire wave state - a ground-based expanding ring triggered when the leap lands. Tracked
    // as plain fields ticked from tick(), same "state fields driven every tick" pattern as the
    // leap flight above.
    private static final double FIRE_WAVE_SPEED_PER_TICK = 5.0 / 20.0; // 5 blocks/sec
    private static final double FIRE_WAVE_MAX_RADIUS = 10.0;
    private static final double FIRE_WAVE_BAND_WIDTH = 0.6;
    private static final float FIRE_WAVE_DAMAGE = 25.0F;
    private static final int FIRE_WAVE_BURN_DURATION_TICKS = 100; // 5 seconds
    private static final float FIRE_WAVE_BURN_DAMAGE_PER_TICK = 2.0F;
    private static final int FIRE_WAVE_BURN_INTERVAL_TICKS = 20;

    private boolean fireWaveActive = false;
    private double fireWaveOriginX;
    private double fireWaveOriginY;
    private double fireWaveOriginZ;
    private double fireWaveElapsedTicks;
    private final Set<UUID> fireWaveHitPlayers = new HashSet<>();

    public ZombieColossusEntity(EntityType<? extends ZombieEntity> entityType, World world) {
        super(entityType, world);
    }

    public static DefaultAttributeContainer.Builder createZombieColossusAttributes() {
        return ZombieEntity.createZombieAttributes()
                .add(EntityAttributes.MAX_HEALTH, 750.0)
                .add(EntityAttributes.ATTACK_DAMAGE, 100.0);
    }

    /** A boss shouldn't die to sunlight-camping. */
    @Override
    protected boolean burnsInDaylight() {
        return false;
    }

    @Override
    protected void initDataTracker(DataTracker.Builder builder) {
        super.initDataTracker(builder);
        builder.add(LEAP_WINDUP_TICKS, 0);
        builder.add(LEAP_FLIGHT_ACTIVE, false);
    }

    /** Ticks remaining before the next leap launches (0 = not preparing one) - read client-side
     *  by the GeckoLib controller to select the leap_windup animation. */
    public int getLeapWindupTicks() {
        return this.dataTracker.get(LEAP_WINDUP_TICKS);
    }

    void setLeapWindupTicks(int ticks) {
        this.dataTracker.set(LEAP_WINDUP_TICKS, ticks);
    }

    /** Whether the boss is currently airborne mid-leap - read client-side by the GeckoLib
     *  controller to select the leap_flight animation (the flight tick counter itself is
     *  server-only travel() state, never synced - same split as SpiderQueenEntity). */
    public boolean isLeapFlightActive() {
        return this.dataTracker.get(LEAP_FLIGHT_ACTIVE);
    }

    @Override
    public AnimatableInstanceCache getAnimatableInstanceCache() {
        return this.geoCache;
    }

    @Override
    public void registerControllers(AnimatableManager.ControllerRegistrar controllers) {
        controllers.add(new AnimationController<>(MAIN_CONTROLLER, 4, this::handleAnimationState)
                .triggerableAnim("smash", SMASH_ANIM)
                .triggerableAnim("rage", RAGE_ANIM)
                .triggerableAnim("earthquake", EARTHQUAKE_ANIM));
    }

    private PlayState handleAnimationState(AnimationTest<ZombieColossusEntity> test) {
        if (test.animatable().getLeapWindupTicks() > 0) {
            return test.setAndContinue(LEAP_WINDUP_ANIM);
        }
        if (test.animatable().isLeapFlightActive()) {
            return test.setAndContinue(LEAP_FLIGHT_ANIM);
        }
        if (test.isMoving()) {
            return test.setAndContinue(WALK_ANIM);
        }
        return test.setAndContinue(IDLE_ANIM);
    }

    /** Deliberately equips NOTHING: the Colossal Warclub is real geometry in the GeckoLib model
     *  now (a "club" bone on the right forearm), so an equipped ItemStack would be redundant -
     *  and vanilla's own random per-difficulty zombie gearing must stay suppressed. The
     *  guaranteed club drop is handled explicitly in dropLoot(). */
    @Override
    protected void initEquipment(Random random, LocalDifficulty localDifficulty) {
    }

    @Override
    protected void initGoals() {
        this.goalSelector.add(1, new EarthquakeAttackGoal(this));
        this.goalSelector.add(2, new RageAttackGoal(this));
        this.goalSelector.add(3, new LeapAttackGoal(this));
        this.goalSelector.add(4, new ColossusAttackGoal(this));
        this.goalSelector.add(5, new WanderAroundFarGoal(this, 1.0));
        this.goalSelector.add(6, new LookAtEntityGoal(this, PlayerEntity.class, 8.0F));
        this.goalSelector.add(6, new LookAroundGoal(this));
        this.targetSelector.add(1, new RevengeGoal(this));
        this.targetSelector.add(2, new ActiveTargetGoal<>(this, PlayerEntity.class, true));
    }

    /**
     * Directly-driven leap, same technique as SpiderQueenEntity.startLeapFlight() - bypasses
     * vanilla's velocity/gravity pipeline entirely and moves exactly per a precomputed table,
     * re-aiming at the live target position every tick.
     */
    void startLeapFlight(double horizontalDistance, Vec3d initialDirection) {
        this.leapFlightTotalTicks = LEAP_FRACTIONS.length;
        this.leapFlightTicksRemaining = this.leapFlightTotalTicks;
        this.leapFlightHorizontalDistance = horizontalDistance;
        this.leapFlightPrevFraction = 0.0;
        this.leapFlightPrevHeight = 0.0;
        this.leapFlightDirection = initialDirection;
        this.dataTracker.set(LEAP_FLIGHT_ACTIVE, true);
    }

    void stopLeapFlight() {
        this.leapFlightTicksRemaining = 0;
        this.dataTracker.set(LEAP_FLIGHT_ACTIVE, false);
    }

    int getLeapFlightTicksRemaining() {
        return this.leapFlightTicksRemaining;
    }

    @Override
    public void travel(Vec3d movementInput) {
        if (!getEntityWorld().isClient() && leapFlightTicksRemaining > 0) {
            performLeapFlightStep();
            return;
        }
        super.travel(movementInput);
    }

    private void performLeapFlightStep() {
        int index = leapFlightTotalTicks - leapFlightTicksRemaining;
        double heightNow = LEAP_HEIGHTS[index];
        double fractionNow = LEAP_FRACTIONS[index];
        double deltaHeight = heightNow - leapFlightPrevHeight;
        double deltaFraction = fractionNow - leapFlightPrevFraction;
        leapFlightPrevHeight = heightNow;
        leapFlightPrevFraction = fractionNow;

        LivingEntity target = this.getTarget();
        if (target != null) {
            Vec3d toTarget = new Vec3d(target.getX() - getX(), 0.0, target.getZ() - getZ());
            if (toTarget.lengthSquared() > 1.0E-7) {
                leapFlightDirection = toTarget.normalize();
            }
        }

        double horizontalStep = leapFlightHorizontalDistance * deltaFraction;
        Vec3d delta = new Vec3d(
                leapFlightDirection.x * horizontalStep, deltaHeight, leapFlightDirection.z * horizontalStep);
        this.move(MovementType.SELF, delta);
        this.velocityDirty = true;

        leapFlightTicksRemaining--;
        if (leapFlightTicksRemaining == 0) {
            this.dataTracker.set(LEAP_FLIGHT_ACTIVE, false);
            startFireWave();
        }
    }

    /** She shouldn't take fall damage from landing her own signature attack. */
    @Override
    public boolean handleFallDamage(double fallDistance, float damageMultiplier, DamageSource damageSource) {
        return false;
    }

    private void startFireWave() {
        this.fireWaveActive = true;
        this.fireWaveOriginX = getX();
        this.fireWaveOriginY = getY();
        this.fireWaveOriginZ = getZ();
        this.fireWaveElapsedTicks = 0.0;
        this.fireWaveHitPlayers.clear();
    }

    @Override
    public void tick() {
        super.tick();
        if (!getEntityWorld().isClient()) {
            if (leapCooldownTicks > 0) {
                leapCooldownTicks--;
            }
            if (rageCooldownTicks > 0) {
                rageCooldownTicks--;
            }
            if (earthquakeCooldownTicks > 0) {
                earthquakeCooldownTicks--;
            }
            if (attackCooldownTicks > 0) {
                attackCooldownTicks--;
            }
            if (fireWaveActive) {
                tickFireWave();
            }
        }
    }

    private void tickFireWave() {
        if (!(getEntityWorld() instanceof ServerWorld serverWorld)) {
            return;
        }
        fireWaveElapsedTicks += 1.0;
        double radius = fireWaveElapsedTicks * FIRE_WAVE_SPEED_PER_TICK;
        if (radius >= FIRE_WAVE_MAX_RADIUS) {
            fireWaveActive = false;
            fireWaveHitPlayers.clear();
            return;
        }

        spawnFireWaveRingParticles(serverWorld, radius);

        double innerRadius = Math.max(0.0, radius - FIRE_WAVE_BAND_WIDTH);
        double outerRadius = radius + FIRE_WAVE_BAND_WIDTH;
        Box searchBox = new Box(
                fireWaveOriginX - outerRadius, fireWaveOriginY - 2.0, fireWaveOriginZ - outerRadius,
                fireWaveOriginX + outerRadius, fireWaveOriginY + 3.0, fireWaveOriginZ + outerRadius);
        for (PlayerEntity player : serverWorld.getEntitiesByClass(PlayerEntity.class, searchBox, PlayerEntity::isAlive)) {
            if (fireWaveHitPlayers.contains(player.getUuid())) {
                continue;
            }
            double dx = player.getX() - fireWaveOriginX;
            double dz = player.getZ() - fireWaveOriginZ;
            double horizontalDistance = Math.sqrt(dx * dx + dz * dz);
            if (horizontalDistance >= innerRadius && horizontalDistance <= outerRadius) {
                fireWaveHitPlayers.add(player.getUuid());
                player.damage(serverWorld, this.getDamageSources().inFire(), FIRE_WAVE_DAMAGE);
                player.setOnFireForTicks(FIRE_WAVE_BURN_DURATION_TICKS);
                BurnDamageManager.applyBurn(
                        player, FIRE_WAVE_BURN_DURATION_TICKS, FIRE_WAVE_BURN_DAMAGE_PER_TICK, FIRE_WAVE_BURN_INTERVAL_TICKS);
            }
        }
    }

    private void spawnFireWaveRingParticles(ServerWorld serverWorld, double radius) {
        int points = 24;
        for (int i = 0; i < points; i++) {
            double angle = (Math.PI * 2.0 * i) / points;
            double x = fireWaveOriginX + Math.cos(angle) * radius;
            double z = fireWaveOriginZ + Math.sin(angle) * radius;
            serverWorld.spawnParticles(ParticleTypes.FLAME, x, fireWaveOriginY + 0.1, z, 1, 0.0, 0.0, 0.0, 0.0);
        }
    }

    @Override
    protected void dropLoot(ServerWorld world, DamageSource damageSource, boolean causedByPlayer) {
        this.dropStack(world, new ItemStack(ModItems.COLOSSAL_WARCLUB));
    }

    @Override
    public int getMonsterLevel() {
        return LEVEL;
    }

    /**
     * The slow, heavy base attack - a fully custom Goal rather than a MeleeAttackGoal subclass,
     * since MeleeAttackGoal has no overridable attack-range hook in this version (confirmed via
     * javap against the real 1.21.11 jar). Range widened from the original 2.0 after playtesting
     * - `Entity.distanceTo()` measures center-to-center, not hitbox-edge-to-edge, so 2.0 against
     * a 1.8-block-wide giant holding a long club left the actual swing looking like it connected
     * well before the hit registered. 4.5 accounts for the boss's own bulk plus club length.
     */
    private static class ColossusAttackGoal extends Goal {
        private static final double ATTACK_RANGE = 4.5;
        private static final double MOVE_SPEED = 1.0;
        private static final int ATTACK_COOLDOWN_TICKS = 40; // 0.5 attacks/sec
        /** The smash animation's club lands at 0.30s (see tools/gen_zombie_colossus_anims.py) -
         *  damage fires on that exact tick instead of instantly on swing start, so what the
         *  player sees and when the number applies finally line up. */
        private static final int SMASH_DAMAGE_DELAY_TICKS = 6;

        private final ZombieColossusEntity colossus;
        private int pendingStrikeTicks = -1;

        ColossusAttackGoal(ZombieColossusEntity colossus) {
            this.colossus = colossus;
            this.setControls(EnumSet.of(Goal.Control.MOVE, Goal.Control.LOOK));
        }

        @Override
        public boolean canStart() {
            LivingEntity target = colossus.getTarget();
            return target != null && target.isAlive();
        }

        @Override
        public boolean shouldContinue() {
            return canStart();
        }

        @Override
        public void start() {
            // NOTE: deliberately does NOT touch the attack cooldown - it lives on the entity
            // (attackCooldownTicks, ticked down centrally) so being preempted by rage/leap/
            // earthquake and resuming no longer resets it (balance-reviewer finding: the old
            // goal-local reset-to-0 quietly inflated real burst damage).
            pendingStrikeTicks = -1;
        }

        @Override
        public void stop() {
            // drop any in-flight strike when preempted - otherwise it would fire, stale, the
            // moment this goal resumes seconds later
            pendingStrikeTicks = -1;
        }

        @Override
        public void tick() {
            LivingEntity target = colossus.getTarget();
            if (target == null) {
                return;
            }
            colossus.getLookControl().lookAt(target, 30.0F, 30.0F);
            double distance = colossus.distanceTo(target);
            if (distance > ATTACK_RANGE) {
                colossus.getNavigation().startMovingTo(target, MOVE_SPEED);
            } else {
                colossus.getNavigation().stop();
            }

            if (pendingStrikeTicks > 0) {
                pendingStrikeTicks--;
                if (pendingStrikeTicks == 0) {
                    pendingStrikeTicks = -1;
                    // small grace on range: the target saw the swing start in range
                    if (target.isAlive() && colossus.distanceTo(target) <= ATTACK_RANGE + 1.0) {
                        target.damage(getServerWorld(colossus),
                                colossus.getDamageSources().mobAttack(colossus), 100.0F);
                    }
                }
                return;
            }

            if (colossus.attackCooldownTicks > 0) {
                return;
            }
            if (distance <= ATTACK_RANGE) {
                colossus.triggerAnim(MAIN_CONTROLLER, "smash");
                pendingStrikeTicks = SMASH_DAMAGE_DELAY_TICKS;
                colossus.attackCooldownTicks = ATTACK_COOLDOWN_TICKS;
            }
        }
    }

    /**
     * Earthquake - the boss's new ground-slam skill: after a sky-high two-handed wind-up
     * (the "earthquake" GeckoLib animation, slam lands at tick 15) the club hits the ground,
     * dealing heavy damage to every player standing in the shockwave radius and visibly
     * shaking the ground - expanding rings of dust-pillar particles bursting out of the actual
     * ground blocks (the same particle vanilla's mace ground-smash uses; purely cosmetic, NO
     * blocks are modified) plus small velocity jolts so nearby players physically feel the
     * ground shudder.
     */
    private static class EarthquakeAttackGoal extends Goal {
        private static final double RADIUS = 9.0;
        private static final float DAMAGE = 100.0F;
        private static final int COOLDOWN_TICKS = 360; // 18 seconds
        private static final int SLAM_TICK = 15;       // = the animation's 0.75s impact
        private static final int SHAKE_DURATION_TICKS = 12;
        private static final int TOTAL_TICKS = 44;     // matches the 2.2s animation
        private static final int RING_POINTS = 20;

        private final ZombieColossusEntity colossus;
        private int elapsedTicks;

        EarthquakeAttackGoal(ZombieColossusEntity colossus) {
            this.colossus = colossus;
            this.setControls(EnumSet.of(Goal.Control.MOVE, Goal.Control.LOOK, Goal.Control.JUMP));
        }

        @Override
        public boolean canStart() {
            if (colossus.earthquakeCooldownTicks > 0 || !colossus.isOnGround()) {
                return false;
            }
            LivingEntity target = colossus.getTarget();
            // only worth casting when the target is actually inside the shockwave radius
            return target != null && target.isAlive() && colossus.distanceTo(target) <= RADIUS - 1.0;
        }

        @Override
        public boolean shouldContinue() {
            return elapsedTicks < TOTAL_TICKS;
        }

        @Override
        public void start() {
            elapsedTicks = 0;
            colossus.getNavigation().stop();
            colossus.triggerAnim(MAIN_CONTROLLER, "earthquake");
            colossus.playSound(SoundEvents.ENTITY_ZOMBIE_AMBIENT, 2.5F, 0.3F);
        }

        @Override
        public void stop() {
            colossus.earthquakeCooldownTicks = COOLDOWN_TICKS;
        }

        @Override
        public void tick() {
            colossus.getNavigation().stop();
            LivingEntity target = colossus.getTarget();
            if (target != null && elapsedTicks < SLAM_TICK) {
                colossus.getLookControl().lookAt(target, 30.0F, 30.0F);
            }
            elapsedTicks++;

            if (elapsedTicks == SLAM_TICK) {
                slam();
            } else if (elapsedTicks > SLAM_TICK && elapsedTicks <= SLAM_TICK + SHAKE_DURATION_TICKS) {
                tickShockwave(elapsedTicks - SLAM_TICK);
            }
        }

        /** The impact tick: sound, damage, and the first ground burst at the boss's feet. */
        private void slam() {
            ServerWorld world = getServerWorld(colossus);
            colossus.playSound(SoundEvents.ITEM_MACE_SMASH_GROUND_HEAVY, 3.0F, 0.6F);
            colossus.playSound(SoundEvents.ENTITY_GENERIC_EXPLODE.value(), 1.5F, 0.5F);
            world.spawnParticles(ParticleTypes.GUST_EMITTER_LARGE,
                    colossus.getX(), colossus.getY() + 0.2, colossus.getZ(), 1, 0.0, 0.0, 0.0, 0.0);

            Box area = colossus.getBoundingBox().expand(RADIUS, 4.0, RADIUS);
            for (PlayerEntity player : world.getEntitiesByClass(PlayerEntity.class, area, PlayerEntity::isAlive)) {
                if (colossus.distanceTo(player) <= RADIUS) {
                    player.damage(world, colossus.getDamageSources().mobAttack(colossus), DAMAGE);
                    // the quake bucks everyone it hits off their feet a little
                    player.addVelocity(0.0, 0.45, 0.0);
                    player.velocityDirty = true;
                }
            }
        }

        /** Expanding ring of dust-pillar bursts out of the real ground blocks, plus small
         *  velocity jolts every few ticks so players inside the radius feel the shaking. */
        private void tickShockwave(int ticksSinceSlam) {
            ServerWorld world = getServerWorld(colossus);
            double radius = RADIUS * ticksSinceSlam / (double) SHAKE_DURATION_TICKS;
            double angleOffset = colossus.getRandom().nextDouble() * Math.PI * 2.0;
            for (int i = 0; i < RING_POINTS; i++) {
                double angle = angleOffset + (Math.PI * 2.0 * i) / RING_POINTS;
                double x = colossus.getX() + Math.cos(angle) * radius;
                double z = colossus.getZ() + Math.sin(angle) * radius;
                spawnGroundBurst(world, x, z);
            }

            if (ticksSinceSlam % 3 == 0) {
                Box area = colossus.getBoundingBox().expand(RADIUS, 4.0, RADIUS);
                for (PlayerEntity player : world.getEntitiesByClass(PlayerEntity.class, area, PlayerEntity::isAlive)) {
                    if (colossus.distanceTo(player) <= RADIUS && player.isOnGround()) {
                        player.addVelocity(
                                (colossus.getRandom().nextDouble() - 0.5) * 0.12,
                                0.06,
                                (colossus.getRandom().nextDouble() - 0.5) * 0.12);
                        player.velocityDirty = true;
                    }
                }
            }
        }

        /** Finds the ground surface near the boss's own Y level and erupts a short dust pillar
         *  of that block's own particles - reads as the ground itself jumping, without touching
         *  any block state. */
        private void spawnGroundBurst(ServerWorld world, double x, double z) {
            int baseY = colossus.getBlockPos().getY();
            for (int dy = 1; dy >= -3; dy--) {
                BlockPos pos = BlockPos.ofFloored(x, baseY + dy, z);
                BlockState state = world.getBlockState(pos);
                if (!state.isAir() && world.getBlockState(pos.up()).isAir()) {
                    world.spawnParticles(
                            new BlockStateParticleEffect(ParticleTypes.DUST_PILLAR, state),
                            x, pos.getY() + 1.05, z, 3, 0.25, 0.1, 0.25, 0.06);
                    return;
                }
            }
        }
    }

    /**
     * The signature leap - a short stationary wind-up (no custom telegraph animation in v1,
     * just navigation frozen plus a growl, matching Spider Queen's "players should be scared"
     * cue) then a directly-driven jump toward the target, dealing damage on landing-contact and
     * spawning the fire wave once the flight ends (see performLeapFlightStep()).
     */
    private static class LeapAttackGoal extends Goal {
        // MIN_RANGE matches ColossusAttackGoal.ATTACK_RANGE exactly - balance-reviewer found a
        // real mechanical dead zone where neither the base attack nor the leap could land,
        // letting a player deny all damage by holding that exact band. Kept in lockstep with
        // the base attack's range (now 4.5, widened after playtesting - see that goal's
        // javadoc) so there's still no gap between "melee reach ends" and "leap range begins".
        private static final double MIN_RANGE = 4.5;
        private static final double MAX_RANGE = 15.0;
        private static final int WINDUP_TICKS = 10;
        private static final int COOLDOWN_TICKS = 200; // 10 seconds
        private static final float LEAP_DAMAGE = 100.0F;

        private final ZombieColossusEntity colossus;
        private int windupTicksRemaining;
        private boolean hasDealtDamageThisLeap;

        LeapAttackGoal(ZombieColossusEntity colossus) {
            this.colossus = colossus;
            this.setControls(EnumSet.of(Goal.Control.MOVE, Goal.Control.JUMP, Goal.Control.LOOK));
        }

        @Override
        public boolean canStart() {
            if (colossus.leapCooldownTicks > 0) {
                return false;
            }
            LivingEntity target = colossus.getTarget();
            if (target == null || !target.isAlive()) {
                return false;
            }
            double horizontalDistance = horizontalDistanceTo(target);
            return horizontalDistance >= MIN_RANGE && horizontalDistance <= MAX_RANGE;
        }

        @Override
        public boolean shouldContinue() {
            LivingEntity target = colossus.getTarget();
            return (windupTicksRemaining > 0 || colossus.getLeapFlightTicksRemaining() > 0)
                    && target != null && target.isAlive();
        }

        @Override
        public void start() {
            colossus.getNavigation().stop();
            windupTicksRemaining = WINDUP_TICKS;
            colossus.setLeapWindupTicks(windupTicksRemaining);
            hasDealtDamageThisLeap = false;
            colossus.playSound(SoundEvents.ENTITY_ZOMBIE_AMBIENT, 2.0F, 0.6F);
        }

        @Override
        public void stop() {
            windupTicksRemaining = 0;
            colossus.setLeapWindupTicks(0);
            colossus.stopLeapFlight();
        }

        @Override
        public void tick() {
            LivingEntity target = colossus.getTarget();
            if (target == null) {
                return;
            }
            colossus.getLookControl().lookAt(target, 90.0F, 90.0F);

            if (windupTicksRemaining > 0) {
                colossus.getNavigation().stop();
                windupTicksRemaining--;
                colossus.setLeapWindupTicks(windupTicksRemaining);
                if (windupTicksRemaining == 0) {
                    launch(target);
                }
                return;
            }

            if (colossus.getLeapFlightTicksRemaining() > 0
                    && !hasDealtDamageThisLeap && target.isAlive()
                    && colossus.getBoundingBox().expand(0.3).intersects(target.getBoundingBox())) {
                target.damage(getServerWorld(colossus), colossus.getDamageSources().mobAttack(colossus), LEAP_DAMAGE);
                hasDealtDamageThisLeap = true;
            }
        }

        private void launch(LivingEntity target) {
            colossus.getNavigation().stop();
            double horizontalDistance = horizontalDistanceTo(target);
            Vec3d direction = new Vec3d(target.getX() - colossus.getX(), 0.0, target.getZ() - colossus.getZ());
            direction = direction.lengthSquared() > 1.0E-7 ? direction.normalize() : colossus.getRotationVec(1.0F);
            colossus.startLeapFlight(horizontalDistance, direction);
            colossus.leapCooldownTicks = COOLDOWN_TICKS;
        }

        private double horizontalDistanceTo(LivingEntity target) {
            double dx = target.getX() - colossus.getX();
            double dz = target.getZ() - colossus.getZ();
            return Math.sqrt(dx * dx + dz * dz);
        }
    }

    /**
     * Three fast strikes in quick succession, only usable in melee range, on its own long
     * cooldown - a periodic burst that preempts the regular attack cadence (higher goal
     * priority, same Control flags, so the goal system arbitrates which one runs). Gets a
     * short wind-up (growl + brief stationary pause) before the first strike -
     * `balance-reviewer` correctly flagged that 300 damage (60% of a fresh character's starting
     * health) with literally zero telegraph and sub-reactable gaps between strikes was a much
     * sharper "you didn't see it coming" burst than anything else in this boss's kit, unlike the
     * leap's explicit, already-reviewed wind-up. This doesn't make the attack dodgeable mid-
     * combo (same "fully committed" precedent as the leap), just gives the player a fair warning
     * before it starts.
     */
    private static class RageAttackGoal extends Goal {
        // Kept in lockstep with ColossusAttackGoal.ATTACK_RANGE (widened to 4.5 after
        // playtesting - see that goal's javadoc) so rage strikes reach exactly as far as the
        // base attack does.
        private static final double RANGE = 4.5;
        private static final int WINDUP_TICKS = 8;
        private static final int COOLDOWN_TICKS = 200; // 10 seconds
        private static final float STRIKE_DAMAGE = 100.0F;
        private static final int[] STRIKE_TICKS = {0, 5, 9}; // within a 10-tick (0.5s) window, after wind-up

        private final ZombieColossusEntity colossus;
        private int windupTicksRemaining;
        private int elapsedTicks;
        private int nextStrikeIndex;

        RageAttackGoal(ZombieColossusEntity colossus) {
            this.colossus = colossus;
            this.setControls(EnumSet.of(Goal.Control.MOVE, Goal.Control.LOOK));
        }

        @Override
        public boolean canStart() {
            if (colossus.rageCooldownTicks > 0) {
                return false;
            }
            LivingEntity target = colossus.getTarget();
            return target != null && target.isAlive() && colossus.distanceTo(target) <= RANGE;
        }

        @Override
        public boolean shouldContinue() {
            return windupTicksRemaining > 0 || nextStrikeIndex < STRIKE_TICKS.length;
        }

        @Override
        public void start() {
            windupTicksRemaining = WINDUP_TICKS;
            elapsedTicks = 0;
            nextStrikeIndex = 0;
            colossus.getNavigation().stop();
            // one triggered animation covers the whole combo: overhead wind-up, then club
            // impacts keyed to this goal's exact strike ticks (8/13/17 after the trigger -
            // see tools/gen_zombie_colossus_anims.py's server-timing contract)
            colossus.triggerAnim(MAIN_CONTROLLER, "rage");
            colossus.playSound(SoundEvents.ENTITY_ZOMBIE_AMBIENT, 2.0F, 0.4F);
        }

        @Override
        public void stop() {
            colossus.rageCooldownTicks = COOLDOWN_TICKS;
        }

        @Override
        public void tick() {
            colossus.getNavigation().stop();
            LivingEntity target = colossus.getTarget();
            if (target != null) {
                colossus.getLookControl().lookAt(target, 90.0F, 90.0F);
            }

            if (windupTicksRemaining > 0) {
                windupTicksRemaining--;
                return;
            }

            if (nextStrikeIndex < STRIKE_TICKS.length && elapsedTicks >= STRIKE_TICKS[nextStrikeIndex]) {
                nextStrikeIndex++;
                if (target != null && target.isAlive() && colossus.distanceTo(target) <= RANGE + 0.5) {
                    target.damage(getServerWorld(colossus), colossus.getDamageSources().mobAttack(colossus), STRIKE_DAMAGE);
                }
            }
            elapsedTicks++;
        }
    }
}
